[profile.default.dotenv]
filename = ".env"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "foundry-chainlink-toolkit/=lib/foundry-chainlink-toolkit/src/"
]
optimizer = true
optimizer_runs = 200
via_ir = true

# ---- Lint overrides (silence the notes you saw) ----
[profile.default.lint]
disable = [
    "unaliased-plain-import",
    "unused-import",
    "unwrapped-modifier-logic",
    "mixed-case-function",
    "screaming-snake-case-immutable",
    "unsafe-typecast"
]
enable = [
    "dead-code",
    "unused-variable",
    "unused-return",
    "reentrancy",
    "unchecked-math"
]

